### ISSUE TITLE
Username included in ban reason

### ISSUE THREAD

**Issue by GotEdit** [yPedx/SuchBans#1]
![image](https://cloud.githubusercontent.com/assets/26687780/24330706/59111352-121c-11e7-8dc6-b6b1a8744faa.png)
I try to look for this in the config file but it is not there. I cannot edit this detail, something on the coding side

**Comment by yPedx** [comment]
Thank you for the report!
I'll look into this and get it foxed asap.
Are you sure you haven't used the variable %player% in the ban reasons?

**Comment by GotEdit** [comment]
I used the default configuration and thst is how it is

**Comment by yPedx** [comment]
Thankfully I've found a solution, and the next version will be released soon!
