### ISSUE TITLE
Error when executing /punish {player}

### ISSUE THREAD

**Issue by SylinsicGaming** [yPedx/SuchBans#10]
Am getting a java.lang.NullPointerException on line 53 and line 245; 245 can be ignored though as it is simply linking to the method which 53 is in.
Here is the error:
[![https://gyazo.com/a55e0b1220e7e17bd8f21132e87ca5c3](https://i.gyazo.com/a55e0b1220e7e17bd8f21132e87ca5c3.png)](https://gyazo.com/a55e0b1220e7e17bd8f21132e87ca5c3)

**Comment by yPedx** [comment]
Please post your config file.

**Comment by SylinsicGaming** [comment]
# SuchBansGUI by yPedx
# Version v5.0.6
# ------------------------------------------------------------------
# Variables:
# #target            <-- The target
# #punisher          <-- The one punishing
# ------------------------------------------------------------------
# Commands and permissions can be found at spigot download page.
# Plugin not working properly? Create an issue at github.com/yPedx/SuchBans/issues
# ------------------------------------------------------------------
# Create / remove any Items you want.
# REQUIRED FORMAT:
#    Slot#:            <-- # = 1-54
#      Name:           <-- What name should the item have?  // Color codes are supported
#      Command:        <-- What command should it execute?  // Do not include a /
#      Item:           <-- What item should it be?          // Block IDs not supported. Example use; DIAMOND_BLOCK 
#      Permission:     <-- Custom permission for your item  // Must have 2 parts! Example: like.this
# ------------------------------------------------------------------
# Use AdvancedStats?
AdvancedStats: false

# What Item should be used for;
Stats: SIGN
Pages: BOOK
Back: BARRIER
Options: NETHER_STAR


Page1:
  Slot1:
    Name: 'Spamming '
    Command: configure me!
    Item: Wood_plank
    Permission: not.specified



---------------------------------
The owner of the server did this - came on to a message asking to configure but was throwing errors so thats why i contacted you xD

**Comment by SylinsicGaming** [comment]
looking at it now, appears to be the command and name bits of slot1

**Comment by SylinsicGaming** [comment]
Found the problem, was an invalid item name, thanks for looking anyway :)

**Comment by yPedx** [comment]
:)
