### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by SylinsicGaming** [yPedx/SuchBans#11]
Hi again.. xD
We are currently using advancedbans for our main banning system as it allows for pre-defined ban/kick messages etc. When I dont include inverted commas for the command definition, it only recognises the word 'kick' so it doesn't know who to kick, but when I do include inverted commas, it thinks #target is the player to be kicked? Any ideas on how to get around this?

**Comment by SylinsicGaming** [comment]
Again, solved it xD,

Have to use " " instead of ' ', ' ' causes it to bug out a bit, might be something to fix for next update? :P

**Comment by yPedx** [comment]
How is it bugging? That you can't use ' ',' ' but "," ?

**Comment by SylinsicGaming** [comment]
when I use these ones; " " the entire command works. However, when I use these ones: ' ', it recognises #target as being a player rather than selecting the target variable -> it tries to kick #target, not the actual player being targeted.

**Comment by yPedx** [comment]
Oh, alright. Watch out for that then :D
