### ISSUE TITLE
SuchBans is difficult to set up.

### ISSUE THREAD

**Issue by Sytanicy** [yPedx/SuchBans#12]
Hi yPedx,
I updated the plugin "Suchbans" but its now difficult to make/fix the config.
can you maybe do like 1 slot (Slot 1,3,4..) Create witch you can copy paste?

Regards, Sytanicy.

**Comment by yPedx** [comment]
There has been setup commands to do the job instead of editing the config. You may do "/sb help edit" to view the commands to edit the GUI in-game. After that you can copy the slot in the config and paste it somewhere else, but of course you can always use the commands. :)

**Comment by Sytanicy** [comment]
Minecraft ID's do not work ?

**Comment by Sytanicy** [comment]
Minecraft block ID's do not work ?

**Comment by yPedx** [comment]
No, block/item ID's does not work.

**Comment by Sytanicy** [comment]
If i click on the gui item http://prntscr.com/f0zvoe "Player not found" im using the Essentials ban system
Config slot 11:
  Slot11:
    Name: '&e&lSterkte 1'
    Command: tempban 4 hours test
    Item: STONE_AXE
    Permission: not.specified

**Comment by yPedx** [comment]
Toy never defined who you were punishing. Use #target after tempban.

**Comment by Sytanicy** [comment]
Okay !

**Comment by Sytanicy** [comment]
Its still not working !?:
Page1:
  Slot11:
    Name: '&e&lSterkte 1'
    Command: tempban #target 1 hour
    Item: STONE_AXE
    Permission: not.specified

**Comment by yPedx** [comment]
The time is formatted as "h" for hour(s).

**Comment by Sytanicy** [comment]
When i do that its not working it replaces everything:
EDITED:Page1:
  Slot11:
    Name: '&e&lSterkte 1'
    Command: tempban #target 1h Test
    Item: STONE_AXE
    Permission: not.specified
But this replaces it automatic if i reload the plugin.
Page1:
  Slot11:
    Name: '&e&lSterkte 1'
    Command: tempban
    Item: STONE_AXE
    Permission: not.specified

**Comment by yPedx** [comment]
1. It replaces this;
```
Slot11:
Name: '&e&lSterkte 1'
Command: tempban #target 1h Test
Item: STONE_AXE
Permission: not.specified
```
with this;
```
Slot11:
Name: '&e&lSterkte 1'
Command: tempban
Item: STONE_AXE
Permission: not.specified
```
2. How are you reloading the plugin?
3. Does the command work now though? If not, check the Essentials documentation for the command. This problem is not in this plugin.

**Comment by Sytanicy** [comment]
Okay

**Comment by Sytanicy** [comment]
If i do it with the normal minecraft command (/ban name reason) its also not working:
Its gonna replace if i do /reload and also /sb reload
From-
Page1:
  Slot11:
    Name: '&e&lSterkte 1'
    Command: ban #target test
    Item: STONE_AXE
    Permission: not.specified
To-
Page1:
  Slot11:
    Name: '&e&lSterkte 1'
    Command: ban
    Item: STONE_AXE
    Permission: not.specified

**Comment by yPedx** [comment]
Do not reload after using in-game commands to create/edit items in the GUI. All changes will be instantly saved. If you want to configure permissions/commands/etc you can also use the in-game commands without reload. The only thing that needs a reload, is when editing the config manually.

**Comment by Sytanicy** [comment]
Ahh sick now it works!

**Comment by Sytanicy** [comment]
Players can open the gui with/pu NAME and see everything. Can it be blocked that they can't ?
And maybe this also in the config:
Show IP in GUI: True/false

**Comment by yPedx** [comment]
**Update**
Players may now **not** use the command if they don't have the permission ( /pu {player} )
Also, there's an option in the config to toggle off advanced stats. A more detailed option will come soon.

**Comment by Sytanicy** [comment]
Oke !
