### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by BlazedFire** [yPedx/SuchBans#13]
Hi!
This isn't really an issue....
How do I punish the 'player' xD?
I tried %player%, #player, player
Which one do I use? :?
 Slot11:
    Name: '&eConfigure me!'
    Command: warn %player% Capitals
    Item: DROPPER
    Permission: sb.caps

**Comment by yPedx** [comment]
This was written in the config as well as a note section on the spigot page. Use #target for the targetted player, and #punisher for the one punishing.

**Comment by BlazedFire** [comment]
Ahh.. That's what confused me... before when I put in #player it would disappear after config reload... I have to put ' start to finish...
Thanks 4 help

**Comment by BlazedFire** [comment]
Also are you able to make a keep-open config thing? So that it doesn't close when you click on nothing?

**Comment by yPedx** [comment]
"keep-open config" ? I believe you mean the GUI.
Clicking air/no item will in the next update do nothing, as well as the punishment to an offline player. Thank you for the idea/suggestion!

**Comment by BlazedFire** [comment]
Awesome!
