### ISSUE TITLE
Unabe to add more slots

### ISSUE THREAD

**Issue by SpyCraft3r** [yPedx/SuchBans#4]
Hello yPedx it seems that I cant add anymore slots to your plugin. It seems to only allow slots 1-9 (S1-S9) trying to add other slots past 9 simply do not work

S9 Command: 'ban %player% Hacked Client - Fly'
S9 Item: FEATHER
S9 Name: '&eFly'

**S10 Command: 'ban %player% Player - Abuse'
S10 Item: WOOL
S10 Name: '&eAbuse'**

**Comment by BlazedFire** [comment]
I experience this too! Please fix!

**Comment by yPedx** [comment]
Unfortunately you cannot change the slots yet, the S1 - S9 & S50 are main and it's not possible to add more. This will be possible in the feature as well as changing all the positions of your items :)

**Comment by BlazedFire** [comment]
Hopefully next update? :3

**Comment by yPedx** [comment]
Who knows ;D

**Comment by SpyCraft3r** [comment]
Thanks mate
