### ISSUE TITLE
tempban command is not working

### ISSUE THREAD

**Issue by RPGGamers** [yPedx/SuchBans#5]
so ban is the only command that is working for the plugin last update i had everything with tempban and it was working perfectly now it keeps giving me a error

**Comment by yPedx** [comment]
Please post the error and your whole config file.

**Comment by RPGGamers** [comment]
so these is the error i get in the console
[09:39:47 ERROR]: Could not pass event InventoryClickEvent to SuchBansGUI v4.3.0
i try uploaing the file but it does not support .yml files so i yest post it here for you
 These is the config file

# ------------------------------------------------------------------
# SuchBansGUI by yPedx
# Version v4.3.0
# ------------------------------------------------------------------
# Colour codes are supported.
# Use %player% to get the player.
# Commands and permissions can be found at spigot download page.
# Plugin not working properly? Create an issue at github.com/yPedx/SuchBans/issues
# ------------------------------------------------------------------
# IMPORTANT: If you want to remove an existing punishment, you have to replace it with
# another Item! (Like the STAINED_GLASS_PANE)
# ------------------------------------------------------------------
# IMPORTANT: When an Item in the GUI is clicked, the action will be logged at the bottom of this config.
# However, the config file will rmeove ALL comments like this. (Don't worry, everything works but these comments are gone
# and this config looks a bit different.)
# ------------------------------------------------------------------
# Punishments
# Here you may change the the name, the command, click sound and Item type.
# Example: S1 = Slot1 (First slot in the GUI)
# All slots in the GUI are under this line.
# ------------------------------------------------------------------
S1 Command: 'tempban 7d %player% Hacked Client - KillAura / Triggerbot'
S1 Item: DIAMOND_SWORD
S1 Name: '&cKillAura / Triggerbot'
S1 Sound: NOTE_PLING

S2 Command: 'tempban 3d %player% Hacked Client - Speed'
S2 Item: SUGAR
S2 Name: '&bSpeed'
S2 Sound: NOTE_PLING

S3 Command: 'tempban 5d %player% Hacked Client - Phase'
S3 Item: IRON_FENCE
S3 Name: '&5Phase'
S3 Sound: NOTE_PLING

S4 Command: 'tempban 7d %player% Hacked Client - Aimbot'
S4 Item: BOW
S4 Name: '&eAimbot'
S4 Sound: NOTE_PLING

S5 Command: 'tempban 5d %player% Hacked Client - X-Ray / Tracers'
S5 Item: DIAMOND_ORE
S5 Name: '&2X-Ray / Tracers'
S5 Sound: NOTE_PLING

S6 Command: 'tempban 5d %player% Hacked Client - AutoClicker'
S6 Item: IRON_SWORD
S6 Name: '&cAutoclicker'
S6 Sound: NOTE_PLING

S7 Command: 'tempban 5d %player% Hacked Client - Reach'
S7 Item: STICK
S7 Name: '&cReach'
S7 Sound: NOTE_PLING

S8 Command: 'tempban 3d %player% Hacked Client - Freecam'
S8 Item: GLASS
S8 Name: '&fFreecam'
S8 Sound: NOTE_PLING

S9 Command: 'tempban 3d %player% Hacked Client - Fly'
S9 Item: FEATHER
S9 Name: '&eFly'
S9 Sound: NOTE_PLING




S10 Command: 'tempban 30m %player% First Time - Swearing / Cursing'
S10 Item: RED_MUSHROOM
S10 Name: '&aSwearing / Cursing'
S10 Sound: NOTE_PLING

S11 Command: 'tempban 1h %player% Second Time - Swearing / Cursing'
S11 Item: RED_MUSHROOM
S11 Name: '&aSwearing / Cursing'
S11 Sound: NOTE_PLING

S12 Command: 'tempban 2h %player% Third Time - Swearing / Cursing'
S12 Item: RED_MUSHROOM
S12 Name: '&aSwearing / Cursing'
S12 Sound: NOTE_PLING

S13 Command: 'tempban 3h %player% Fourth Time - Swearing / Cursing'
S13 Item: RED_MUSHROOM
S13 Name: '&aSwearing / Cursing'
S13 Sound: NOTE_PLING

S14 Command: 'tempban 4h %player% Fifth Time - Swearing / Cursing'
S14 Item: RED_MUSHROOM
S14 Name: '&aSwearing / Cursing'
S14 Sound: NOTE_PLING

S15 Command: 'tempban 5h %player% Six Time - Swearing / Cursing'
S15 Item: RED_MUSHROOM
S15 Name: '&aSwearing / Cursing'
S15 Sound: NOTE_PLING

S16 Command: 'tempban 6h %player% Seven Time - Swearing / Cursing'
S16 Item: RED_MUSHROOM
S16 Name: '&aSwearing / Cursing'
S16 Sound: NOTE_PLING

S17 Command: 'tempban 7h %player% Eighth Time - Swearing / Cursing'
S17 Item: RED_MUSHROOM
S17 Name: '&aSwearing / Cursing'
S17 Sound: NOTE_PLING

S18 Command: 'tempban 1d %player% Too Much - Swearing / Cursing'
S18 Item: RED_MUSHROOM
S18 Name: '&aSwearing / Cursing'
S18 Sound: NOTE_PLING




S19 Command: ''
S19 Item: STAINED_GLASS_PANE
S19 Name: ' '
S19 Sound: NOTE_PLING

S20 Command: ''
S20 Item: STAINED_GLASS_PANE
S20 Name: ' '
S20 Sound: NOTE_PLING

S21 Command: ''
S21 Item: STAINED_GLASS_PANE
S21 Name: ' '
S21 Sound: NOTE_PLING

S22 Command: ''
S22 Item: STAINED_GLASS_PANE
S22 Name: ' '
S22 Sound: NOTE_PLING

S23 Command: ''
S23 Item: STAINED_GLASS_PANE
S23 Name: ' '
S23 Sound: NOTE_PLING

S24 Command: ''
S24 Item: STAINED_GLASS_PANE
S24 Name: ' '
S24 Sound: NOTE_PLING

S25 Command: ''
S25 Item: STAINED_GLASS_PANE
S25 Name: ' '
S25 Sound: NOTE_PLING

S26 Command: ''
S26 Item: STAINED_GLASS_PANE
S26 Name: ' '
S26 Sound: NOTE_PLING

S27 Command: ''
S27 Item: STAINED_GLASS_PANE
S27 Name: ' '
S27 Sound: NOTE_PLING




S28 Command: ''
S28 Item: STAINED_GLASS_PANE
S28 Name: ' '
S28 Sound: NOTE_PLING

S29 Command: ''
S29 Item: STAINED_GLASS_PANE
S29 Name: ' '
S29 Sound: NOTE_PLING

S30 Command: ''
S30 Item: STAINED_GLASS_PANE
S30 Name: ' '
S30 Sound: NOTE_PLING

S31 Command: ''
S31 Item: STAINED_GLASS_PANE
S31 Name: ' '
S31 Sound: NOTE_PLING

S32 Command: ''
S32 Item: STAINED_GLASS_PANE
S32 Name: ' '
S32 Sound: NOTE_PLING

S33 Command: ''
S33 Item: STAINED_GLASS_PANE
S33 Name: ' '
S33 Sound: NOTE_PLING

S34 Command: ''
S34 Item: STAINED_GLASS_PANE
S34 Name: ' '
S34 Sound: NOTE_PLING

S35 Command: ''
S35 Item: STAINED_GLASS_PANE
S35 Name: ' '
S35 Sound: NOTE_PLING

S36 Command: ''
S36 Item: STAINED_GLASS_PANE
S36 Name: ' '
S36 Sound: NOTE_PLING




S37 Command: ''
S37 Item: STAINED_GLASS_PANE
S37 Name: ' '
S37 Sound: NOTE_PLING

S38 Command: ''
S38 Item: STAINED_GLASS_PANE
S38 Name: ' '
S38 Sound: NOTE_PLING

S39 Command: ''
S39 Item: STAINED_GLASS_PANE
S39 Name: ' '
S39 Sound: NOTE_PLING

S40 Command: ''
S40 Item: STAINED_GLASS_PANE
S40 Name: ' '
S40 Sound: NOTE_PLING

S41 Command: ''
S41 Item: STAINED_GLASS_PANE
S41 Name: ' '
S41 Sound: NOTE_PLING

S42 Command: ''
S42 Item: STAINED_GLASS_PANE
S42 Name: ' '
S42 Sound: NOTE_PLING

S43 Command: ''
S43 Item: STAINED_GLASS_PANE
S43 Name: ' '
S43 Sound: NOTE_PLING

S44 Command: ''
S44 Item: STAINED_GLASS_PANE
S44 Name: ' '
S44 Sound: NOTE_PLING

S45 Command: ''
S45 Item: STAINED_GLASS_PANE
S45 Name: ' '
S45 Sound: NOTE_PLING




S46 Sound: NOTE_BASS

S47 Command: ''
S47 Item: STAINED_GLASS_PANE
S47 Name: ' '
S47 Sound: NOTE_PLING

S48 Command: ''
S48 Item: STAINED_GLASS_PANE
S48 Name: ' '
S48 Sound: NOTE_PLING

S49 Command: ''
S49 Item: STAINED_GLASS_PANE
S49 Name: ' '
S49 Sound: NOTE_PLING

S50 Item: ANVIL
S50 Sound: NOTE_BASS

S51 Command: ''
S51 Item: STAINED_GLASS_PANE
S51 Name: ' '
S51 Sound: NOTE_PLING

S52 Command: ''
S52 Item: STAINED_GLASS_PANE
S52 Name: ' '
S52 Sound: NOTE_PLING

S53 Command: ''
S53 Item: STAINED_GLASS_PANE
S53 Name: ' '
S53 Sound: NOTE_PLING

S54 Command: ''
S54 Item: STAINED_GLASS_PANE
S54 Name: ' '
S54 Sound: NOTE_PLING


# Punishment log / recent activities
# ------------------------------------------------------------------

PunishmentLog:

**Comment by RPGGamers** [comment]
if i remove the word temp it works fine

**Comment by yPedx** [comment]
hm, I'll look into this. Thank you for the report!

**Comment by RPGGamers** [comment]
thank you very much for the quick respond my friend

**Comment by yPedx** [comment]
Note: Do you have a ban system? This is only a GUI to execute commands from other plugins. Could you post a list of your plugins?

**Comment by RPGGamers** [comment]
ok

**Comment by RPGGamers** [comment]
Adfly.jar	3.6 MB	Tue, 21 Mar 2017 00:21:56 GMT
AnimatedScoreboard.jar	66.2 kB	Wed, 05 Apr 2017 09:39:49 GMT
BowsPlus (1).jar	46.2 kB	Tue, 21 Mar 2017 19:35:55 GMT
BungeePortals.jar	19.0 kB	Mon, 06 Mar 2017 03:56:16 GMT
buycraftx-spigot-10.1.4.jar	2.4 MB	Sun, 12 Mar 2017 02:53:29 GMT
ChatControl.jar	168.9 kB	Fri, 07 Apr 2017 09:59:55 GMT
ChestShop.jar	616.9 kB	Sat, 10 Dec 2016 14:13:23 GMT
Citizens.jar	1.5 MB	Fri, 24 Mar 2017 02:48:21 GMT
Clearlag.jar	108.1 kB	Sat, 10 Dec 2016 15:35:20 GMT
CommandNPC.jar	19.7 kB	Fri, 24 Mar 2017 02:48:32 GMT
CratesPlus-4.3.1.jar	152.4 kB	Fri, 07 Apr 2017 09:54:56 GMT
Crazy Auctions[v1.2.1].jar	63.3 kB	Fri, 07 Apr 2017 10:03:36 GMT
Crazy Enchantments[v1.7.8.3].jar	337.0 kB	Fri, 07 Apr 2017 10:05:07 GMT
CustomOreGen.jar	44.8 kB	Sun, 26 Feb 2017 20:21:07 GMT
CustomShop.jar	62.0 kB	Fri, 07 Apr 2017 10:02:45 GMT
dynmap-2.4.jar	4.0 MB	Mon, 13 Feb 2017 06:51:45 GMT
EssentialsX-2.0.1.jar	1.1 MB	Fri, 10 Mar 2017 08:35:05 GMT
EssentialsXAntiBuild-2.0.1.jar	13.9 kB	Fri, 10 Mar 2017 08:35:05 GMT
EssentialsXChat-2.0.1.jar	12.3 kB	Fri, 10 Mar 2017 08:35:05 GMT
EssentialsXGeoIP-2.0.1.jar	117.3 kB	Fri, 10 Mar 2017 08:41:20 GMT
EssentialsXProtect-2.0.1.jar	18.9 kB	Fri, 10 Mar 2017 08:35:05 GMT
EssentialsXSpawn-2.0.1.jar	17.7 kB	Fri, 10 Mar 2017 08:41:28 GMT
HolographicDisplays.jar	484.2 kB	Sat, 04 Mar 2017 06:09:40 GMT
iConomyRecreation pre-8.0.jar	167.2 kB	Sun, 26 Feb 2017 23:05:57 GMT
KitAdder.jar	31.5 kB	Wed, 14 Dec 2016 08:06:11 GMT
mcMMO.jar	1.2 MB	Sun, 05 Mar 2017 07:17:37 GMT
Multiverse-Core-2.5.jar	1.6 MB	Wed, 14 Dec 2016 04:12:07 GMT
Multiverse-NetherPortals-2.5.jar	42.8 kB	Sat, 10 Dec 2016 16:44:16 GMT
Multiverse-Portals-2.5.0-SNAPSHOT.jar	103.7 kB	Sat, 25 Feb 2017 04:52:13 GMT
nuvotifier-universal-2.3.4.jar	1.5 MB	Fri, 10 Mar 2017 21:28:57 GMT
PAC.jar	288.1 kB	Sun, 05 Mar 2017 06:04:45 GMT
PermissionsEx-1.23.4.jar	706.0 kB	Sat, 10 Dec 2016 13:29:39 GMT
PlaceholderAPI.jar	100.8 kB	Wed, 05 Apr 2017 09:39:49 GMT
PlayerSkills.jar	49.4 kB	Fri, 07 Apr 2017 09:39:50 GMT
PowerNBT.jar	255.8 kB	Wed, 29 Mar 2017 03:25:41 GMT
ProtocolLib.jar	1.4 MB	Thu, 22 Dec 2016 06:15:42 GMT
safetrade-1.0.13.jar	102.3 kB	Mon, 27 Mar 2017 18:13:05 GMT
SignEdit.jar	55.6 kB	Mon, 20 Mar 2017 17:45:05 GMT
SilkSpawners.jar	224.2 kB	Mon, 13 Mar 2017 13:45:35 GMT
SimpleAPI.jar	354.5 kB	Fri, 24 Mar 2017 15:11:13 GMT
SimplePets.jar	440.5 kB	Fri, 07 Apr 2017 09:53:38 GMT
SmartBans-v1.0.2.jar	20.3 kB	Wed, 15 Mar 2017 23:16:01 GMT
StackMob.jar	121.7 kB	Fri, 07 Apr 2017 09:52:29 GMT
SuchBansGUI.jar	26.0 kB	Fri, 07 Apr 2017 10:06:31 GMT
SuperbVote-0.3.3.jar	1.2 MB	Fri, 10 Mar 2017 21:29:14 GMT
uSkyBlock.jar	1.0 MB	Wed, 01 Mar 2017 03:18:42 GMT
Vault.jar	290.0 kB	Sat, 10 Dec 2016 14:13:20 GMT
Warps.jar	39.6 kB	Fri, 24 Mar 2017 04:31:57 GMT
worldedit-bukkit-6.1.5.jar	1.6 MB	Sat, 10 Dec 2016 14:12:06 GMT
worldguard-6.2.jar

**Comment by yPedx** [comment]
Does the plugin "Smartbans" have /tempban? Please post the **whole** error in console.

**Comment by RPGGamers** [comment]
yes it does

**Comment by RPGGamers** [comment]
this is all the errors i have
[10:09:35 ERROR]: Could not pass event InventoryClickEvent to SuchBansGUI v4.3.0
[10:09:38 ERROR]: Could not pass event InventoryClickEvent to SuchBansGUI v4.3.0
[10:09:42 ERROR]: Could not pass event InventoryClickEvent to SuchBansGUI v4.3.0
[10:09:45 ERROR]: Could not pass event InventoryClickEvent to SuchBansGUI v4.3.0
[10:09:52 ERROR]: Could not pass event InventoryClickEvent to SuchBansGUI v4.3.0

**Comment by yPedx** [comment]
I think I found the issue, you have written the command wrong :P It's supposed to be:
**/tempban <player> <length> <reason>**
but you did:
**tempban 3d %player% Hacked Client - Speed**
Notice where you put the time and player name.

**Comment by RPGGamers** [comment]
in console the rest is runing fine but that error i get it when i click on the ban icon on the gui

**Comment by RPGGamers** [comment]
like i said the command tempban in the plugin is not working i can do /tempban in my console and chat without a problem and in the plugin ban works is yest tempban does not register

**Comment by RPGGamers** [comment]
so is the plugin my friend cause is the same command i was using before the update you did yesterday

**Comment by RPGGamers** [comment]
let me change it and see if it works the way you said

**Comment by yPedx** [comment]
I installed the plugin myself, and the command form "tempban player time reason" works fine. The other one however, does not work.

**Comment by RPGGamers** [comment]
hey my friend let me tell you something about you plugin i think you don't know but by default
this command already has the (/) in the GUI if i add the (/) then is going to show in the GUI two (//)
DEFUALT   S1 Command: 'tempban 7d %player% Hacked Client - KillAura / Triggerbot'
NEW Changes S1 Command: '/tempban 7d %player% Hacked Client - KillAura / Triggerbot'
and error for the change
[10:19:58 ERROR]: Could not pass event InventoryClickEvent to SuchBansGUI v4.3.0

**Comment by yPedx** [comment]
Don't use the **/** of course.. the **/** was to show it was a command.

**Comment by RPGGamers** [comment]
like i said if i remove the word (temp) then the plugin works

**Comment by yPedx** [comment]
Do you want to go into further details by making a call on discord or something? Seems like something is interfering with the plugin. It works completely fine for me.

**Comment by RPGGamers** [comment]
ok i have skype

**Comment by RPGGamers** [comment]
RPG Gamers my picture is Bleach Anime
