### ISSUE TITLE
unable to get the latest version

### ISSUE THREAD

**Issue by matpl1996** [yPedx/SuchBans#6]
Hello,

I am running a local server to build my server and I want to use you're plugin, but I see that there is a new version but I am unable to get it, when I download the plugin it runs on version 4.2.0, how can I fix this problem, I really want to able to custom the GUI Menu, but I don't think version 4.2.0 support it, do you know how to ger the latest version?

**Comment by yPedx** [comment]
You can download the latest version here; https://www.spigotmc.org/resources/suchbansgui-advanced-punishment-gui.38443/history

**Comment by yPedx** [comment]
Sorry, didn't mean to close issue xD

Have you replaced the config file and the .jar?

**Comment by matpl1996** [comment]
I downloaded it from the page you send, I only got the jar file, and when I load the jar file it creates this 
file. Do I need to replace the config file with the text on the spigot page?

`# SuchBansGUI by yPedx
# Version v4.2.0
#
# Colour codes are supported.
# Use %player% to get the player.
#
# Commands and permissions can be found at spigot download page.
#
# Plugin not working properly? Create an issue at github.com/yPedx/SuchBans/issues
#
# ---------------------------------------------------------------------------------

# Punishments
# Here you may change the the name, the command and the Item type.
# Example: S1 = Slot1 (First slot in the GUI)
# NOTICE: You cannot change any S# (# = random number)

S1 Command: 'ban %player% Hacked Client - KillAura / Triggerbot'
S1 Item: DIAMOND_SWORD
S1 Name: '&cKillAura / Triggerbot'

S2 Command: 'ban %player% Hacked Client - Speed'
S2 Item: SUGAR
S2 Name: '&bSpeed'

S3 Command: 'ban %player% Hacked Client - Phase'
S3 Item: IRON_FENCE
S3 Name: '&5Phase'

S4 Command: 'ban %player% Hacked Client - Aimbot'
S4 Item: BOW
S4 Name: '&eAimbot'

S5 Command: 'ban %player% Hacked Client - X-Ray / Tracers'
S5 Item: DIAMOND_ORE
S5 Name: '&2X-Ray / Tracers'

S6 Command: 'ban %player% Hacked Client - AutoClicker'
S6 Item: IRON_SWORD
S6 Name: '&cAutoclicker'

S7 Command: 'ban %player% Hacked Client - Reach'
S7 Item: STICK
S7 Name: '&cReach'

S8 Command: 'ban %player% Hacked Client - Freecam'
S8 Item: GLASS
S8 Name: '&fFreecam'

S9 Command: 'ban %player% Hacked Client - Fly'
S9 Item: FEATHER
S9 Name: '&eFly'

S50 Item: ANVIL`

**Comment by yPedx** [comment]
Download the newest version, delete the SuchbansGUI folder in your plugins folder. Reload/restart your server and it should all be good.

**Comment by matpl1996** [comment]
Did not work, I am downloaden V5.0.1, putting it in my plugins folder, deleted al the SychbansGUI folders and it's still launching in my logs the 4.2.0

**Comment by matpl1996** [comment]
A list of current plugins that I have now:
Automessage
Clearlag
Dynmap
Essentials ( all of them )
Hidecustomplugins
jobs3.8.2
NocheatPlus
Permissions
ProtocolLib
Staff+
SuchBansGUI
Vault
Worldedit
Worldguard

**Comment by yPedx** [comment]
Are you sure you moved the plugin into the plugins folder?
Go in-game and do /sb version

**Comment by matpl1996** [comment]
[SuchBans] You are currently running SuchBans V4.2.0

The message I get

**Comment by yPedx** [comment]
Mhm, this is something you'll have to figure out yourself. I cannot do anything from this side :/ Probably something with your computer / you're doing something wrong.

**Comment by matpl1996** [comment]
I have tested to download it on my MSI and Macbook and 2 times I have the same problem, could it be with the spigot version? or something else?

**Comment by yPedx** [comment]
I'll go ahead and download the plugin myself and see.

**Comment by yPedx** [comment]
Oh no! I've uploaded the wrong file!!
I apologie so much! I'm fixing it right now.
