### ISSUE TITLE
I think I found a little bug

### ISSUE THREAD

**Issue by matpl1996** [yPedx/SuchBans#7]
I am back :)

The plugin is working but when I add an item and click on it, I am rederected to page 2, If I add an Item to page 2, when clicking on it, I am rederected to the optionsPage.

my second question is, when doing the command /pu Name, what type of code do I need to insert in the Command for kicking the player: %player%, target, ? none are working for me. maybe I am wrong.

Here is the config I made to test it:

```
AdvancedStats: true
Stats: SIGN
Pages: BOOK
Back: BARRIER
Options: NETHER_STAR
Page1:
  Slot1:
    Name: ban
    Command: kick player
    Item: DIAMOND_BLOCK
    Permission: Suchbans.test
  Slot2:
    Name: test
    Command: give %player% 46
    Item: TNT
    Permission: Suchbans.test
Page2:
  Slot1:
    Name: ban
    Command: kick
    Item: DIAMOND_BLOCK
    Permission: Suchbans.test
OptionsPage:
  Slot1:
    Name: ban
    Command: give %player% 46
    Item: TNT
    Permission: Suchbans.test
```

**Comment by yPedx** [comment]
The variables are;
#target
#punisher
I'll look into the other bug.

**Comment by yPedx** [comment]
Did you add the items through in-game commands, or manually changing the config?

**Comment by matpl1996** [comment]
Manually in the config

**Comment by yPedx** [comment]
Alright, trying to fix it atm.
I strongly apologize for the problems xD

**Comment by matpl1996** [comment]
No problem, here to find the bugs so you can improve you're plugin ;)
Really great plugin, I see a future for it

**Comment by yPedx** [comment]
Just found out the custom permissions doesn't work either.. Thank you for reporting this :D

**Comment by yPedx** [comment]
Unfortunately this will take some time :( I'll try to do it as fast as I can!

**Comment by matpl1996** [comment]
Take you're time, better to take you're time and do it good than rush it and do it bad :)

**Comment by yPedx** [comment]
Issue solved, as well as some other bugs :) Thank you for the report!
