### ISSUE TITLE
how to perform commands on players

### ISSUE THREAD

**Issue by matpl1996** [yPedx/SuchBans#8]
I am sorry for having al those question, but I have a problem for performming commands with the variables

the problem with using #target is that it makes a line comment.

this is my code ant every time I execute it, The player target is not found.
`Page1:
  Slot1:
    Name: test1
    Command: kick target
    Item: DIAMOND_BLOCK
    Permission: Suchbans.test
  Slot2:
    Name: test2
    Command: give target 46
    Item: TNT
    Permission: Suchbans.test
Page2:
  Slot1:
    Name: ban
    Command: kick
    Item: DIAMOND_BLOCK
    Permission: Suchbans.test
OptionsPage:
  Slot1:
    Name: ban
    Command: give %target% 46
    Item: TNT
    Permission: Suchbans.test
PunishmentLog:
- ============== [2017/apr/20 21:31:27] =====================
- Punisher >> Nitmat
- Target >> nitmat
- Command >> /give target 46
- ==============================================
- ''
- ============== [2017/apr/20 21:31:27] =====================
- Punisher >> Nitmat
- Target >> nitmat
- Command >> /kick target
- ==============================================
- ''`

someting I tested is to use the in game commands, wish are not adding any items or commands to the GUI.

**Comment by yPedx** [comment]
From what I can see here, you've used "target"instead of "#target" in the commands. Also, could you tell me what command you did when trying to add commands/names/perms etc. ?

**Comment by matpl1996** [comment]
So I found how it works, but found a little bug. when using the commands in game I needed to perform them like that: /sb create page1 slot1 TNT, My mistake in the beginning was by doing the commands like: /sb create 1 1 TNT, what was not working, my bad -_-

when doing the command after each other it added the code in the config at the end like this:
`page1:
  Slotslot3:
    Name: 'Test '
    Item: 'TNT'
    Command: 'give #target 46 '
    Permission: test.test`

something weird with the Slotslot3

The second problem I found is that I need to use ' ' for the codes to find the target

`  Slot2:
    Name: test
    Command: 'give #target 46'
    Item: TNT
    Permission: Suchbans.test`

Tis command is working perfect!!

**Comment by matpl1996** [comment]
I am going to make a template for you to use if you want, so other people have it more easy to config this beautiful plugin

**Comment by yPedx** [comment]
You need an uppercase P in "Page" :D Always uppercase when defining the page.

**Comment by yPedx** [comment]
I had a problem before when there was some items in the GUI as standard. For some reason they couldn't be removed.. So I dropped the standard items :/

**Comment by matpl1996** [comment]
Here is a Config I made, it is working perfectly :) Took it from you're old config file, it might help you to tell other people how the plugin works :)

```
# SuchBansGUI by yPedx
# Version v5.0.5
# ------------------------------------------------------------------
# Variables:
# #target            <-- The target
# #punisher          <-- The one punishing
# ------------------------------------------------------------------
# Commands and permissions can be found at spigot download page.
# Plugin not working properly? Create an issue at github.com/yPedx/SuchBans/issues
# ------------------------------------------------------------------
# Create / remove any Items you want.
# REQUIRED FORMAT:
#    Slot#:            <-- # = 1-54
#      Name:           <-- What name should the item have?  // Color codes are supported
#      Command:        <-- What command should it execute?  // Do not include a /
#      Item:           <-- What item should it be?          // Block IDs not supported. Example use; DIAMOND_BLOCK
#      Permission:     <-- Custom permission for your item  // Must have 2 parts! Example: like.this
# ------------------------------------------------------------------
# Use AdvancedStats?
AdvancedStats: true
Stats: SIGN
Pages: BOOK
Back: BARRIER
Options: NETHER_STAR
Page1:
  Slot1:
    Name: '&cKillAura / Triggerbot'
    Command: 'ban #target Hacked Client - KillAura / Triggerbot'
    Item: DIAMOND_SWORD
    Permission: Suchbans.ban
  Slot2:
    Name: '&bSpeed'
    Command: 'ban #target Hacked Client - Speed'
    Item: SUGAR
    Permission: Suchbans.speed
  Slot3:
    Name: '&5Phase'
    Command: 'ban #target Hacked Client - Phase'
    Item: IRON_FENCE
    Permission: Suchbans.phase
  Slot4:
    Name: '&eAimbot'
    Command: 'ban #target Hacked Client - Aimbot'
    Item: BOW
    Permission: Suchbans.aimbot
  Slot5:
    Name: '&2X-Ray / Tracers'
    Command: 'ban #target Hacked Client - X-Ray / Tracers'
    Item: DIAMOND_ORE
    Permission: Suchbans.tracers
  Slot6:
    Name: '&cAutoclicker'
    Command: 'ban #target Hacked Client - AutoClicker'
    Item: IRON_SWORD
    Permission: Suchbans.autoclicker
  Slot7:
    Name: '&cReach'
    Command: 'ban #target Hacked Client - Reach'
    Item: STICK
    Permission: Suchbans.reach
  Slot8:
    Name: '&fFreecam'
    Command: 'ban #target Hacked Client - Freecam'
    Item: GLASS
    Permission: Suchbans.freecam
  Slot9:
    Name: '&eFly'
    Command: 'ban #target Hacked Client - Fly'
    Item: FEATHER
    Permission: Suchbans.fly
Page2:
OptionsPage:
PunishmentLog:

```

**Comment by matpl1996** [comment]
I have a suggestion, example when kicking a player there is a extra slot like advanced stats that tells if the players already had been kickt, how many times, ... like muted, kicked, banned, tempbanned
Something like the logs but directly on the persons GUI in game

**Comment by yPedx** [comment]
Might be cool :D 
And;

> I had a problem before when there was some items in the GUI as standard. For some reason they couldn't be removed.. So I dropped the standard items :/
