### ISSUE TITLE
SuchBans Permission

### ISSUE THREAD

**Issue by IBadSlayerI** [yPedx/SuchBans#9]
I am clicking the Item and I get a message saying, "You are not allowed to use this Item!" I have tested this without my op. When I'm op it works fine.
____________________________________________
- http://prntscr.com/ez8yz7

- http://prntscr.com/ez8z7h
_____________________________________________

(I have to convert the config.yml to config.txt)
(Will support a screenshot as it being in .yml)

[config.txt](https://github.com/yPedx/SuchBans/files/948079/config.txt)

- http://prntscr.com/ez94sp

**Comment by yPedx** [comment]
Did you give the rank the permission using an uppercase letter as you set in the config?

**Comment by IBadSlayerI** [comment]
Yes, I may have thought it was (CaSe-Sensitive) so I made it all perfect and it's still the same.

[Sorry for the late reply]

**Comment by yPedx** [comment]
Could you post your updated config anf permissions file? I'll see what I can find out about this bug.

**Comment by IBadSlayerI** [comment]
Alright, will post it on pastebin. Will only provide the permission from Trainee. I you need full permission config please inform me.

PermissionsEX: https://pastebin.com/4PGw4hQQ

SuchBans: https://pastebin.com/09jFg8kS

**Comment by yPedx** [comment]
Nor sure if capital letters work, try using only lowercase in the permission node.

**Comment by IBadSlayerI** [comment]
Same thing happens. I even changed the permission node lowercase in suchbans and still doesn't work for  that certain group.

**Comment by yPedx** [comment]
When you changed to lowercase, did you do it in the permissions file?
I'll test and see what I can figure out :)

**Comment by IBadSlayerI** [comment]
Yes did both and okay.

**Comment by yPedx** [comment]
Ah!
What version are you using?

**Comment by yPedx** [comment]
Issue fixed :)
